[package]
name = "crawler"
version = "0.1.0"
authors = ["Luis Wirth <lwirth2000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# for cargo flamegraph
[profile.release]
debug = true

[dependencies]
futures = "0.3.4"
tokio = { version = "0.2.19", features = ["full"] }

reqwest = "0.10.4"
html5ever = "0.25.1"
url = "2.1.1"

clap = "2.33.0"
log = "0.4.8"
fern = { version = "0.6.0", features = ["colored"] }
chrono = "0.4.11"
